name: gymtrack_app
description: Aplicaci칩n de gimnasio con IA y Firebase
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.0
  timezone: ^0.9.2
  awesome_notifications: ^0.10.1

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.3
  image_picker: ^1.0.4

  # Dependencias para persistencia local
  shared_preferences: ^2.1.0

  # Detecci칩n de estado de la red (online/offline)
  connectivity_plus: ^4.0.0

  # Estado y configuraci칩n
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
 
  # Gr치ficos
  fl_chart: ^0.66.2

  # IA (Gemini)
  google_generative_ai: ^0.4.7
  dart_openai: ^5.1.0

  # Extras
  http: ^1.2.1
  intl: 0.20.2
  google_fonts: ^6.1.0
  uuid: ^4.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/profile_placeholder.png
    - assets/badges/




    