// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ZmX2tE9VtacJ0t9kdcUu6OkfoMYeqDI',
    appId: '1:911795652569:web:88a691d1992d2263273bc8',
    messagingSenderId: '911795652569',
    projectId: 'gymtrack-19174',
    authDomain: 'gymtrack-19174.firebaseapp.com',
    storageBucket: 'gymtrack-19174.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs2eO1E7mKvM1q1qFIasB0yMB_7GJoGzM',
    appId: '1:911795652569:android:096889fc8234ad8b273bc8',
    messagingSenderId: '911795652569',
    projectId: 'gymtrack-19174',
    storageBucket: 'gymtrack-19174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHb0-DJbqnHUYU9yHGrUqLeqZp17EqX20',
    appId: '1:911795652569:ios:46e472bffb97cdf2273bc8',
    messagingSenderId: '911795652569',
    projectId: 'gymtrack-19174',
    storageBucket: 'gymtrack-19174.firebasestorage.app',
    iosBundleId: 'com.example.gymtrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHb0-DJbqnHUYU9yHGrUqLeqZp17EqX20',
    appId: '1:911795652569:ios:46e472bffb97cdf2273bc8',
    messagingSenderId: '911795652569',
    projectId: 'gymtrack-19174',
    storageBucket: 'gymtrack-19174.firebasestorage.app',
    iosBundleId: 'com.example.gymtrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ZmX2tE9VtacJ0t9kdcUu6OkfoMYeqDI',
    appId: '1:911795652569:web:405f95a4037a4719273bc8',
    messagingSenderId: '911795652569',
    projectId: 'gymtrack-19174',
    authDomain: 'gymtrack-19174.firebaseapp.com',
    storageBucket: 'gymtrack-19174.firebasestorage.app',
  );
}
